dist: focal # Ubuntu 20.04 LTS
language: ruby

cache:
  - apt
  - bundler

rvm:
  - 2.7.4

env:
  global:
    - SERVICE_NAME=alpha_project
    - ARG_COMPOSE_WAIT_VER=2.9.0
    - DB_VERSION=5.7.33
    - DB_PASSWORD=db_password
    - RUBYGEMS_VERSION=3.2.27
    - BUNDLER_VERSION=1.17.3

git:
  depth: 1

services:
  - docker

before_install:
  - gem update --system ${RUBYGEMS_VERSION}
  - gem --version # 3.1.2
  - gem install bundler -v ${BUNDLER_VERSION}
  - bundler --version # 2.2.21

install:
  - bundle config set --local deployment 'true'
  - |
    BUNDLE_WITHOUT=production \
    BUNDLE_PATH=vendor/cache \
    bundler install --local

before_script:
  - |
    docker run --rm --detach \
      --env MYSQL_ROOT_PASSWORD=${DB_PASSWORD} \
      --network=host \
      mysql:${DB_VERSION}

  - |
    docker build . \
      --build-arg ARG_COMPOSE_WAIT_VER=${ARG_COMPOSE_WAIT_VER} \
      --tag ${SERVICE_NAME}/wait:${ARG_COMPOSE_WAIT_VER} \
      -f dockerfiles/Dockerfile.wait

  - |
    docker run --rm \
      --env WAIT_HOSTS=127.0.0.1:3306 \
      --network=host \
      ${SERVICE_NAME}/wait:${ARG_COMPOSE_WAIT_VER}

  - |
    CI=true \
    BUNDLE_PATH=vendor/cache \
    bundle exec rake db:create \
      db:migrate

jobs:
  include:
    - stage: Application correctness
      script: |
        CI=true \
        BUNDLE_PATH=vendor/cache \
          bundle exec rake test
      name: Test suite
